version: "3.8"
services:
  blowfish-apache:
    image: loveless2u/phpcrypfish:latest
    container_name: blowfish-apache
    ports:
      - "80:80"
    networks:
      - my-network

  docker-apache:
    image: my-php-site:latest
    container_name: docker-apache
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge