version: "3.8"
services:
  blowfish-apache:
    image: loveless2u/phpcrypfish:latest
    container_name: blowfish-apache
    ports:
      - "80:80"
    networks:
      - my-network

  docker-apache:
    image: my-php-site:latest
    container_name: docker-apache
    ports:
      - "8080:8080"
    networks:
      - my-network

  zap:
    image: ictu/zap2docker-weekly
    container_name: zap-container
    command: ["zap.sh", "-daemon", "-port", "8090", "-host", "0.0.0.0", "-config", "api.disablekey=true", "-ajaxSpider", "-scan", "-recursive", "-spider", "1", "-url", "http://docker-apache/index.php"]
    ports:
      - "8090:8090"
    depends_on:
      - blowfish-apache
    networks:
      - my-network

networks:
  my-network:
    driver: bridge